[pytest]
asyncio_mode = auto
testpaths = tests
filterwarnings =
    ignore:'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16:DeprecationWarning
    ignore:'asyncio.set_event_loop_policy' is deprecated and slated for removal in Python 3.16:DeprecationWarning
    ignore:'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16:DeprecationWarning
    ignore:datetime.datetime.utcnow\(\) is deprecated and scheduled for removal in a future version.*:DeprecationWarning
